### ISSUE TITLE
baseclient.py has stopped working.. KeyError: 'ns0'

### ISSUE THREAD

**Issue by JacobHJ** [rozzac90/betdaq#21]
Hi. I’m having issues running the following code, which has been working flawlessly until recently:

from betdaq.apiclient import APIClient
api = APIClient('username', 'password')
sport_ids = api.marketdata.get_sports()

error:

Traceback (most recent call last):
  File "C:\Users\UK\AppData\Local\Programs\Python\Python37\lib\site-packages\zeep\xsd\schema.py", line 172, in get_ns_prefix
    return self._prefix_map_custom[prefix]
KeyError: 'ns0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\UK\AppData\Local\Programs\Python\Python37\lib\site-packages\zeep\xsd\schema.py", line 174, in get_ns_prefix
    return self._prefix_map_auto[prefix]
KeyError: 'ns0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\UK\Desktop\Betdaq test.py", line 2, in <module>
    api = APIClient('username', password')
  File "C:\Users\UK\AppData\Local\Programs\Python\Python37\lib\site-packages\betdaq\apiclient.py", line 8, in __init__
    super(APIClient, self).__init__(username, password)
  File "C:\Users\UK\AppData\Local\Programs\Python\Python37\lib\site-packages\betdaq\baseclient.py", line 13, in __init__
    self.initialise_type_factories()
  File "C:\Users\UK\AppData\Local\Programs\Python\Python37\lib\site-packages\betdaq\baseclient.py", line 33, in initialise_type_factories
    self.readonly_types = self.readonly_client.type_factory('ns0')
  File "C:\Users\UK\AppData\Local\Programs\Python\Python37\lib\site-packages\zeep\client.py", line 238, in type_factory
    return Factory(self.wsdl.types, 'type', namespace)
  File "C:\Users\UK\AppData\Local\Programs\Python\Python37\lib\site-packages\zeep\client.py", line 78, in __init__
    self._ns = types.get_ns_prefix(namespace)
  File "C:\Users\UK\AppData\Local\Programs\Python\Python37\lib\site-packages\zeep\xsd\schema.py", line 176, in get_ns_prefix
    raise ValueError("No such prefix %r" % prefix)
ValueError: No such prefix 'ns0'

Thanks a lot for any kind of attention.
Best regards 
Jacob

**Comment by JacobHJ** [comment]
changing the url of the WSDL file in baseclient.py to:
'https://api.betdaq.com/v2.0/API.wsdl'
solved my issue.

**Comment by JacobHJ** [comment]
changing the url of the WSDL file in baseclient.py to:
'https://api.betdaq.com/v2.0/API.wsdl'
solved my issue.
